name: nlu-project
channels:
    - conda-forge
    - pytorch
    - defaults
dependencies:
    - python=3.6.0
    - numpy
    - matplotlib
    - nltk
    - jupyter
    - jupyter_contrib_nbextensions
    - pytorch
    - cuda80
    - torchvision
    - pip
    - pip:
        - plac
        - ujson
        - jsonlines
        - git+https://github.com/pytorch/text
        - git+https://github.com/lanpa/tensorboard-pytorch

