name: nlu-project
channels:
    - conda-forge
    - soumith
    - defaults
dependencies:
    - python=3.6.0
    - numpy
    - matplotlib
    - jupyter
    - jupyter_contrib_nbextensions
    - pytorch
    - cuda80
    - torchvision
    - spacy
    - pip
    - pip:
        - plac
